### ISSUE TITLE
KeyError: 'regularizer'

### ISSUE THREAD

**Issue by rockywind** [ignaciorlando/cnn-dr-kaggle#23]
Hi,My configure is ubuntu16.04+python3+tensorflow1.0.
When I run the scipt:/experiment/main.py.
The error occurs.
`
Traceback (most recent call last):
  File "main.py", line 200, in <module>
    main(data_path,output_path,config_file_path)
  File "main.py", line 64, in main
    model = vgg16.build((image_shape[0], image_shape[1]), config['architecture'])
  File "/home/wxq/disk/14-cnn-dr-kaggle-master/core/models/vgg16.py", line 124, in build
    regularizer=config['regularizer'],
  File "/usr/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'regularizer'
`
Thank you and sorry for again if the answer is obvious!

**Comment by ndazeo** [comment]
Hi @rockywind, which command line argument are you passing to the script?

**Comment by rockywind** [comment]
Hi @ndazeo ,I solved the problem when I chosen the script"config_mod8_aug_drop_l2.ini"
